### ISSUE TITLE
Table with plot: Deleting rows not working correctly

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#318] opened 2022-04-05 23:17 UTC
Deziree and I both experienced issues with deleting rows. I was unable to delete any rows when I only had two rows. Is this by design? Maybe we require two rows? Everything else seems to work for me. Dez, had a situation where deleting the last row was actually deleting the first row.

**Comment by dezidizon** [comment] 2022-04-05 23:40
This issue seemed to have occurred while also testing copying and pasting in the table. Attached is a video demonstrating the issue with deleting rows. I tried to delete the bottom row and it deleted the top row. 

https://user-images.githubusercontent.com/47678178/161867697-f1222854-c05d-4753-9f98-a960e28476c3.mp4

**Comment by HenryGeorgist** [comment] 2022-04-08 18:59
you dont have a row selected - so it deletes the first row.

**Comment by Brennan1994** [comment] 2022-04-13 16:15
This is odd. I'm unable to reproduce that behavior on the current main. Unless someone snuck in and fixed this, It seems like there might be a version issue. Are you able to reliably reproduce this on your machine @dezidizon ?

**Comment by codymccoy** [comment] 2022-04-13 16:54
I am unable to reproduce this. Based on the values in the table in the video, it looks like Dez was using pasted in values. Maybe there is something with copy and paste and delete. I tried pasting data in and then deleting rows, and it all behaved normal for me. Unless someone can reproduce it, lets call it non reproduceable and move on.

**Comment by Brennan1994** [comment] 2022-04-13 18:38
closing because I could not reproduce. We can open it up again if it pops up

**Closed by Brennan1994** 2022-04-13 18:38 UTC
