### ISSUE TITLE
Content Damage Appears to be Computing Incorrectly in the Structure Detail Files

### ISSUE THREAD

**Issue by rtle76** [HydrologicEngineeringCenter/HEC-FDA#1134] opened 2024-08-22 15:42 UTC
In comparing 1.4.3 to 2.0, we're consistently seeing big differences in the content damage computed in the structure detail files. 2.0 has higher damage values in the middle of the curve, but converges with 1.4.3 on the far upper end.

The image below shows the divergence of damage estimates in the structure detail file. 2.0 is the curve with higher damage.
![image](https://github.com/user-attachments/assets/72ff249d-a117-4170-b4a2-7c4d34cb7fbe)

I've tested the calculations and 1.4.3 shows the damage result I'd expect when following the content value, percent damage, and then content damage. 

The models can be found here: \\share.hec.usace.army.mil\USACE\Nugent\ForJordan\DamageUncertaintyInvestigations\Muncie

**Comment by rnugent3** [comment] 2024-08-22 20:35
I have confirmed that I like the content damage values in the 1.4.3 file better.

**Comment by rnugent3** [comment] 2024-08-22 20:36
Our structure damage values in the 2.0 structure detail file match the structure damage values in the 1.4.3 structure detail file perfectly, but the content damage values in the 2.0 structure detail file are different from the content damage values in the 1.4.3 structure detail file.

**Comment by rnugent3** [comment] 2024-08-22 20:39
We have a unit test that a structure correctly integrates with occupancy types to calculate content damage for a given WSE.

https://github.com/HydrologicEngineeringCenter/HEC-FDA/blob/dfb88970ecb9a7b92d3cd1e8e31b7bf28497e51b/HEC.FDA.ModelTest/unittests/structures/StructureShould.cs#L58

**Comment by rnugent3** [comment] 2024-08-22 20:41
Troubleshooting this issue is complicated because the values that we print out to the structure detail file are calculated separately from the compute. 

We run the big compute with uncertainty, and then if the user wants the structure detail file, we run through a deterministic compute and collect the results in a format ready for a csv file.

**Comment by rnugent3** [comment] 2024-08-22 23:02
found it. the new paired data search doesn't work with the way that the details are produced. paired data f function returns the wrong percent damage.

**Comment by rnugent3** [comment] 2024-08-22 23:03
this change caused the bug
![image](https://github.com/user-attachments/assets/d5ac80fe-066d-477e-98e1-9070b7f03b37)

**Comment by rnugent3** [comment] 2024-08-22 23:03
I think I can rearrange the code in a way that works with this f function correctly.

**Comment by rnugent3** [comment] 2024-08-23 01:54
The attached file is the structure detail file. The first row is pre bug fix, the second row is post bug fix. Observe that the rows are the same, except for the content damage. 

You can confirm that for a depth above first floor elevation for this structure at the AEP 0.2 is about 3.96ft; with a RES1-1SNB deterministic content depth-percent damage function, percent content damage is about 25.56%; the content value is 100% of structure value which is $117,356.30, so content damage is about $29,996, which is the value post bug fix. The value pre bug fix for this structure/depth above FFE is $32,893 because the percent content damage was wrong as a result of the bug in paireddata.f(). 

![image](https://github.com/user-attachments/assets/90c3b7e7-10ad-46bc-8cac-a2eb090b855d)

[WOPStructureStageDamageDetails.csv](https://github.com/user-attachments/files/16720907/WOPStructureStageDamageDetails.csv)

**Closed** 2024-09-04 17:25 UTC
Labels: PRIORITY
