### ISSUE TITLE
Adding histogram to table with plot

### ISSUE THREAD

**Issue by codymccoy** [HydrologicEngineeringCenter/HEC-FDA#563] opened 2022-10-05 22:28 UTC
The stage damage returns a UPD that is of type IHistogram. This is not currently supported by the table with plot control. 

I think we need to do something similar to _DeterministicOnly. We would add an option for _HistogramOnly
![image](https://user-images.githubusercontent.com/47757848/194174669-9c093d91-6e53-4cec-bbe7-f5a73a093c47.png)

The SetPairedData needs to be updated as well. This method needs to look more like the "Initialize" method where we check if it is _DeterministicOnly, _HistogramOnly, or normal. This way we don't add the histogram option to all the tables in FDA.
![image](https://user-images.githubusercontent.com/47757848/194174982-fb679577-3475-4bdd-ae1f-4d6a491764af.png)

Then when we go to create the stage damage rows we would set the computeComponentVM to HistogramOnly
![image](https://user-images.githubusercontent.com/47757848/194175301-3247edde-63a8-41e0-a1f2-8d5f6bf8f9d7.png)

The above is pretty simple. The harder part will probably be adding the new UI controls that support that option in the table and plot. @rnugent3 will describe what that should look like. ie: what columns should be in the table.

**Comment by codymccoy** [comment] 2022-10-06 16:58
Instead of adding a new boolean every time we want a special table with plot, we could turn it into an enum.
enum TableDistributionOptions
DeterministicOnly,
HistogramOnly

Then if/when we want another one, it will be easier to update. Just add another one to the enum.

**Comment by rnugent3** [comment] 2022-10-06 18:21
![image](https://user-images.githubusercontent.com/25163165/194389501-3d667d65-13c1-4758-b65e-aec7ed4dc138.png)

**Comment by codymccoy** [comment] 2022-10-13 16:44
I think this is working correctly. I am not sure why both the 5% and the 95% are both 1 when the mean is 0. I'm sure i am using pretty bad data that is going into the compute. This should be tried using better data to see if we are getting the correct values.

![image](https://user-images.githubusercontent.com/47757848/195656164-e84d47f3-51cb-4d93-9b01-cd82d59955d2.png)

I will round the numbers to 3 decimal places as part of another github issue.

This is completed in branch Bug/HistogramTableWithPlot

**Comment by rnugent3** [comment] 2022-11-04 19:00
We need to investigate why the stage-damage functions are coming back like this. I am using good data and am getting the same thing. Once we get good stage-damage functions, then we can test this.

**Comment by Brennan1994** [comment] 2022-11-10 20:30
closing this as the issue is now captured in #615

**Closed by Brennan1994** 2022-11-10 20:30 UTC
Labels: enhancement
